# Generated by Django 4.1.2 on 2022-10-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=32)),
                ('lastName', models.CharField(max_length=32)),
                ('Class', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=64)),
            ],
        ),
    ]
