# Generated by Django 4.1.2 on 2022-10-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_student_email_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Class',
            field=models.CharField(max_length=62),
        ),
    ]
