# Generated by Django 4.1.2 on 2022-10-30 00:41

from django.db import migrations, models
import django.db.models.deletion
import endpoint.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'Parent',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64, validators=[endpoint.models.check_name])),
                ('last_name', models.CharField(max_length=64, validators=[endpoint.models.check_name])),
                ('class_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='endpoint.parent')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('students', models.ManyToManyField(blank=True, related_name='subjects', to='endpoint.student')),
            ],
            options={
                'db_table': 'Subject',
            },
        ),
    ]
